language: node_js
node_js:
  - '8.9.0'
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 634499ef3bf7c412bbf28bb2d79948983960bde0  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
before_script:
  - npm install
script: npm run deploy
